### ISSUE TITLE
Install OpenMapTiles on OHM-owned EC2

### ISSUE THREAD

**Issue by danrademacher** [Open-Historical-Map-Labs/openhistoricaltiles#1]
See fork at https://github.com/OpenHistoricalMap/openmaptiles, consult with @mojodna with questions

**Comment by gregallensworth** [comment]
Now that the OMT service is basically up on port `8080` we need to groom it a little:

- [x] Set up a service wrapper for tessera, so it will start automatically after a reboot. Reboot to make sure it works.
- [x] Set up Apache etc. so we may host other content.
- [x] Set up the Apache proxy so that the Tessera on `:8080` is visible on port 80; don't just run tessera on 80, as that wouldn't provide HTTPS support when the time comes
- [x] Test & document the use of this new (publicly available) service with Maputnik.

Then HTTPS for the modern web:
- [x] choose a hostname for this service, as the AWS hostname isn't nice, and set up DNS for it
- [x] set up Certbot / LetsEncrypt and get it going, so all traffic is forced to HTTPS

**Comment by gregallensworth** [comment]
Closed issue #2 as it overlaps very strongly with this one here, and achieving one achieved the other as well.

**Comment by gregallensworth** [comment]
Change of plans on the URI routing. It looks to be significant, to reconfigure Tessera and Express so as to properly support a sub-folder URL structure such as `/vectortiles/` There is no built-in configuration to prepend a "path prefix" for purposes of generating the `tiles` URL, and the work to program Tessera and/or Express to auto-detect such a path would be beyond the scope of this project.

So, the whole site is routed over:
http://ec2-18-209-171-18.compute-1.amazonaws.com/#16/47.6054/-122.3343
This is exactly the same as http://ec2-18-209-171-18.compute-1.amazonaws.com:8080/#16/47.6054/-122.3343

This is still done with Apache, as a simple TCP redirect patch would not provide HTTPS capability when that time comes.

**Comment by sethfitz** [comment]
Tessera does support prefixing, but it needs to use a configuration file instead of taking a URI on the command line. This will output the source on `/vectortiles/{z}/{x}/{y}.pbf`:

`tessera.json` (supports multiple sources on different paths; see https://github.com/mojodna/tessera#configuration for options):

```json
{
  "/vectortiles": "tmsource:///path/to/whatever.tm2source"
}
```

```
tessera -c tessera.json
```

(Sitting on the root is just fine, just wanted to clarify our options.)

**Comment by gregallensworth** [comment]
Hey, cool. I spent an hour trying to figure out how to make these pieces do that... I'll aim for the /vectortiles/ URI again. That would keep open the possibility of adding non-Tessera content to the server. Thanks for the note.

**Comment by gregallensworth** [comment]
Hey @tsinn   Want to give it a try in Maputnik?

The new OHM URL should be http://ec2-18-209-171-18.compute-1.amazonaws.com/

**Comment by gregallensworth** [comment]
FYI, the HTTPS & hostname choices are now something of a blocker.

Maputnik runs over HTTPS, however this site does not yet. As such: "Mixed Content: The page at 'https://maputnik.github.io/editor/#15/47.6076/-122.3368' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://ec2-18-209-171-18.compute-1.amazonaws.com/'. This request has been blocked; the content must be served over HTTPS."

I can proceed with a non-HTTPS demo in #4 but we really should get HTTPS set up.

**Comment by gregallensworth** [comment]
Tagging @rwarren2 in regards to setting up DNS.

Please set up a new domain hostname record `vtiles.openhistoricalmap.org` Set this as a CNAME record pointing to *ec2-18-209-171-18.compute-1.amazonaws.com*

**Comment by danrademacher** [comment]
This is now working: http://vtiles.openhistoricalmap.org/ and should be ready for https

**Comment by gregallensworth** [comment]
Apache config is all set.

All requests are redirected to the proper OHM hostname.

All non-HTTPS requests are redirected to HTTPS.

Confirmed that the `gh-pages` demos load these tiles A-OK.

**Comment by gregallensworth** [comment]
Reopen: Confirmed that the tilejson at https://vtiles.openhistoricalmap.org/index.json is still giving out a `http` URL and not a proper HTTPS one. Need to dig deeper into Tessera to fix it.

Should be as easy as setting `X-Forwarded-Proto` and `X-Forwarded-Host` in Apache, which I see Tessera is programmed to heed when constructing the tile URL template.

**Comment by gregallensworth** [comment]
And, proxy config updated. Now Tessera is handing out the proper URL with vtiles and HTTPS, and this should work in Maputnik.
