### ISSUE TITLE
Set up regular diff consumption

### ISSUE THREAD

**Issue by danrademacher** [Open-Historical-Map-Labs/openhistoricaltiles#13]
We now have daily/hourly/minutely diffs back up here:
http://dump.openhistoricalmap.org/replication/

From our last conversation it _might_ be very simple to just "turn on" diff consumption in OpenMaptiles, and Seth thought the minutelies would be small enough to use those.

**Comment by gregallensworth** [comment]
I'm not seeing as mechanism to "turn on" anything in OMT. It's more of a documented process, than a running service. If there are settings to run a diff, it would be part of a larger ecosystem of scheduled tasks, to download something and then to run the relevant parts of the OMT process. I'll start looking into that.

**Comment by gregallensworth** [comment]
Some preliminary discoveries, based of Googling OSM and imposm3, and thumbing through the OMT source code repositories...

* In the initial data import, the `-diff` flag should have been present so as to set up some additional behaviors in imposm3 in the future. Judging by the script, "true" is the default if not set, but the provided `.env` file defines `DIFF_MODE=false` So I may need to backtrack all the way to the beginning, and re-import everything from scratch, in order to enable diffs handling at all?

* The **import-osm** docker image, has a *config.json* with a hardcoded URL for the OSM server, and for a daily schedule. https://github.com/openmaptiles/import-osm/blob/master/config.json As such, one clear step is to fork the *import-osm* utility and change the OHM replication URL, and change OMT's `docker-compose.yaml` to use this new version.

* The OMT command would be `docker-compose run update-osm` https://github.com/openmaptiles/import-osm/blob/master/import_update.sh which would check for a set of diffs and apply them all. Reference:  https://imposm.org/docs/imposm3/latest/tutorial.html#updating and https://github.com/openmaptiles/import-osm/blob/master/import_update.sh

* I think that tessera does some caching of vector tiles? After importing diffs, Tessera should be restarted. Since this can take a full minute and would be an interruption in tile service, perhaps this should not be done overly often?

**Comment by sethfitz** [comment]
Rather than forking `import-osm`, you can map an alternative `config.json` into the container using a `volume`:

`config.json` (in `openmaptiles/openmaptiles`, aka this repo):

```json
{
    "replication_url": "http://dump.openhistoricalmap.org/replication/minute/",
    "replication_interval": "1m"
}
```

```patch
diff --git i/docker-compose.yml w/docker-compose.yml
index ae931f8..05aff55 100644
--- i/docker-compose.yml
+++ w/docker-compose.yml
@@ -38,6 +38,7 @@ services:
      - ./data:/import
      - ./build:/mapping
      - cache:/cache
+     - ./config.json:/usr/src/app/config.json
   import-osmborder:
     image: "openmaptiles/import-osmborder:0.4"
     env_file: .env
```

```bash
$ docker-compose run --rm import-osm bash
WARNING: The BBOX variable is not set. Defaulting to a blank string.
Creating network "openmaptiles_postgres_conn" with the default driver
root@7ab7e3fdf5fb:/usr/src/app# cat config.json
{
    "replication_url": "http://dump.openhistoricalmap.org/replication/minute/",
    "replication_interval": "1m"
}
```

**Comment by sethfitz** [comment]
tessera has an in-memory cache, so it does need to be restarted to clear that (presumably after `update-osm` completes, during which it will render "old" data). It restarts fairly quickly, but it could be an interruption nonetheless. A nice improvement would be to have tessera listen for `SIGHUP` and clear its cache in response without needing to restart (to be clear, it doesn't do this yet).

(I'm assuming we can safely target minutely diffs since OHM data doesn't change all that often, but I'm curious how long `import-osm` takes to run after edits have been made that need to trickle though various generalized tables.)

**Comment by danrademacher** [comment]
OK, this is up and running and we've confirmed OK for now at 30-60 min refresh as experienced by user (accounting for both webserver and potential client side browser caching)
