### ISSUE TITLE
Replace OSM borders in OpenMapTiles import with OHM borders

### ISSUE THREAD

**Issue by danrademacher** [Open-Historical-Map-Labs/openhistoricaltiles#14]
The problem is that OpenMapTiles pulls in OSM borders (and maybe coastlines?) separate from later import of other OSM data. 

@mojodna posted these references in Slack:
https://github.com/trailbehind/osmborder-docker
https://github.com/pnorman/osmborder

@gregallensworth confirmed now that he is purging OSM borders on import, but now we need to pull in OHM borders.

**Comment by gregallensworth** [comment]
This is now in place. The README has been updated in two places (setting up, and updating OHM) to include the steps of running our forked `import-osmborder` tools.

References:
https://github.com/OpenHistoricalMap/import-osmborder
https://github.com/OpenHistoricalMap/osmborder-docker
https://github.com/OpenHistoricalMap/import-osm

The documentation updates includes steps about **updating** but that's part of #13 which is not working at this time.


Some metrics relevant to other planning, in regards to regular updates per #13

Since planet files are often not done until fairly late in the day, and take several hours, they are fetched from the previous day. Example: Today being 2018-01-02, the 2018-01-01 file was fetched.

The *makecsv-osmborder* step takes 20-30 minutes, as it must fetch the entire OHM planet file and extract the borders from it. This runtime is likely to increase as OHM grows.

**Comment by jeffreyameyer** [comment]
W00t!!

**Comment by timwaters** [comment]
edits: the README that was updated is located in the https://github.com/OpenHistoricalMap/openmaptiles repo

**Comment by danrademacher** [comment]
Closing this out as done -- specific related todo over in #16
