### ISSUE TITLE
Reset min date on the slider demos to lowest possible (0?)

### ISSUE THREAD

**Issue by danrademacher** [Open-Historical-Map-Labs/openhistoricaltiles#40]
Looks like this is an almost instant change in the demo params, right?

For low end of "When am I?" and low end of time-slider, let's allow this to be "0" or "1" whichever works.

**Comment by gregallensworth** [comment]
- [x] rename `datespan` to `range` to be consistent with wording throughout the code and documentation

- [x] Demos change range to `[0, CurrentYear]`
  - [x] MBGL demo
  - [x] Leaflet demo

- [x] fix breakages due to years not being 4 digits; tests so far have always had 4 digits, never gone to <1000
  - [x] MBGL control
  - [x] Leaflet wrapper

**Comment by gregallensworth** [comment]
MBGL demo:

Date range changed to `[ 0, currentyear ]` and will change with each calendar year.

Default view is http://localhost:9000/demo/ which thanks to `UrlHashWriter` will update to something close to  http://localhost:9000/demo/#14.600/40.80623/-73.91894/1920,0-2019

Internal rename of the `range` parameter, and updated docs.

Reworked date filter logic, to pad out years to 4 digits, e.g. the year 718 would be represented by the bookends "0718-01-01" and "0718-12-31"

**Comment by gregallensworth** [comment]
Leaflet demo:

https://openhistoricalmap.github.io/openhistoricaltiles/leaflet-control-mbgltimeslider/demo/

Date range is now `[ 0, currentyear ]` same as MBGL demo.

Changed to `datespan` parameter to `range`.

Confirmed that other behaviors such as the casting to 4 digit years, is handled by the underlying MBGL control which has been upgraded.
