### ISSUE TITLE
Remove the OSM-borders tool

### ISSUE THREAD

**Issue by danrademacher** [Open-Historical-Map-Labs/openhistoricaltiles#48]
Broken out from #35. After #47 is done (which implies wholly new borders in maps and upstream data) then we strip out the OSM borders tool

**Comment by gregallensworth** [comment]
Notes:

Directory is `/home/ubuntu/OPENMAPTILES/openhistoricaltiles`

The `ohmboundaries_service.sh` script loads borders. It is triggered via a cronjob (scheduled task) which fires `makecsv-osmborder``import-osmborder` and then the custom SQL script `/home/ubuntu/OPENMAPTILES/openmaptiles/layers/boundary/boundary.sql`

Once borders are really being loaded, these scripts should be deleted. As it stands, they have been disabled for some time since the last server reboot...
